sudo: false
language: node_js
node_js:
- '5.11'
- '6'
env:
- NODE_ENV=test
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  on:
    branch: master
    node: '5.11'
  app: bionikspoon-sumo-survey
  api_key:
    secure: N7eJS9MOKczVoCf9n23dL0w3ZPtNbJOEmYlXsSPIMqVyI4oy6wUBoXKiK3CndAVD0yW+8YTBxf4YeqbiH6s0YvU7sP1wCWn2+3tHJGRjDHs5wtW4lmatPRBakXxuwknWjXj6EmWQ2WG61ciQNgzsEf9oRlbPqqIu6xDdIgTD/cTzJ4Nl8RJkdZp1v6DnthhZJhec3KL+Cr6oxshs6JHDzBZyAcJZLvbsJioIotzNpVbW0Mbb72DevpRm9uQnubGlN5sKTzESh0PMPzJkZvWfphYGxCZ9OYMfWqv+yp189XziJlW+y+3joDTKuPPS5nI+BbrF1Ck89mEIIJ0Llubt36deNJ9an1n1RG8uenwOvQ6mFBU4ZilSr5pjUeW5sScM/2/c/ba0q20m7g/iJIgFGkxzBZTYdeFPfck1zMCw4ncbleITHz0yvDR72rJJDdyk3rwoUv/onTk4cncBZnE6jr+Dt32GaZEzDZohqeyzePvvwXzPPwm/T+oAHVi94kFQ/wDnmU101L6633xbFrH7twI820O+Pfl3rmBntl4ctFF8bXx1y7qL/KY3OJb61XNO1e/59xKHR7FyHwyOFSZnb/TJ7P0rWvg8eHwgWLnoSpbirCy6kYnz+6ipNq64MMAyPhFciotfVZe9deI8TgnGcdwJ6RlEYkx8bZuA7QgyVAc=
