sudo: false
language: node_js
node_js:
- '5.11'
- '6'
env:
- NODE_ENV=test TRAVIS_CI=TRUE CXX=g++-4.8
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_2b46ddb74751_key -iv $encrypted_2b46ddb74751_iv -in deploy_key.enc -out deploy_key -d
before_deploy:
- export NODE_ENV=production
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- mv deploy_key ~/.ssh
- ssh-add ~/.ssh/deploy_key
- git clean -x -d -f
- chmod +x ./bin/deploy
- npm install strongloop
deploy:
  provider: script
  on:
    branch: master
    node: '5.11'
  skip_cleanup: true
  script: ./bin/deploy
