sudo: false
language: node_js
node_js:
- '5.11'
- '6'
env:
  matrix:
  - NODE_ENV=test CXX=g++-4.8
  global:
    secure: QruUkSDNizERlHnDOy8XhOu+bRrVGju4E7l92MvxHMAKE+uClgY2uMm3jumwUbMwUczZ6wk2UINSoH6UtPr8/aLnVJeM+B09s40P4qdu/QBokmBwp6Tg1OzzHuZFUGASiPdC/9p6rzv9k8rMTXeUd/jxUEhSQgAwNgwpBf+cXD51vyC1FJxYcPvFoYJIj9djBXluhS3zvlllAd+xTe7wdfbvdCsQbFy5OzGFjvLDzi67zYfkTGyOMQjuaDOXGxNRsvDzLiLrpulbWI2odjfRdU6A0feGmIvZbUjs893wkqYb4fi42c6neiyN+slldl8hp00tTm1q7VeBYlYjDICHYoqdjVPDGHUT2jV3mhlCGi6HO6MXrDh3DTTYAimqtEKP5ilCRjNs7GDdjie0NLtn9KTaeD6g7Z7Ygh2dUVpI4LnA6ZQJmqtGX3gp+++BYjBB29d3qd/GQ3TIkoZOsqITIFYujQ9cRn1UdH79evDvXrwxz54bPEzg1pBSEnncGenYUgfvu3Zm6aaeS7KSCGZNx5KJTXtzSQDM2BaIHeb5w0dYyEuuDtPtfQVaMXFSBJO6MotHAMqncqwDc9WJJ8ci3qqHkq8bkUqnSBBH4TKXV+sa3+GVr8VeO9kpoC7MvtrIYxYg8IoRBAazlhQ/k9SkRlFySBy40ztP9mwlGTIWMoA=
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_deploy:
- export NODE_ENV=production
- ./bin/repo
- git checkout -b deploy
- git clean -x -d -f
- npm install --ignore-scripts
- npm install gulp-cli
- npm run build
- npm prune --production
- ./bin/commit
- git push -q upstream HEAD:deploy
deploy:
  provider: script
  on:
    branch: master
    node: '5.11'
  skip_cleanup: true
  script: "./bin/deploy"
